### ISSUE TITLE
Get Ready for Maven release of the 2.0.0 version

### ISSUE THREAD

**Issue by pitbulk** [onelogin/java-saml#50]
- [x] Cleanup the project and be ready for Maven [51](https://github.com/onelogin/java-saml/issues/51)
- [x] Review issues with PowerMock [52](https://github.com/onelogin/java-saml/issues/52)
- [x] Remove core servlet dependency [65](https://github.com/onelogin/java-saml/issues/65)
- [x] Documentation: [49](https://github.com/onelogin/java-saml/issues/49)
- [x] Make v2.0.0 the master branch.
- [ ] Publish on Maven central

**Comment by pitbulk** [comment]
Finally!!!  http://repo2.maven.org/maven2/com/onelogin/java-saml/2.0.0/
